syntax on
set tabstop=4
set expandtab
set shiftwidth=4
set shiftround

autocmd! BufNewFile,BufRead *.pde setlocal ft=arduino

autocmd FileType ruby setlocal ts=2 sts=2 sw=2

syntax enable
colorscheme monokai
set number
